language: php
os: 
  - linux

php:
  - '7.1'

before_script:
  - npm install
  - composer install

script:
  - npm run production

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build_production
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  repo: regionhalland/styleguide-docs
  target_branch: master